/**
 * Full emoji palette matching iOS / Android keyboard order.
 * Organised by standard Unicode categories:
 *   Smileys & Emotion → People & Body → Animals & Nature →
 *   Food & Drink → Travel & Places → Activities →
 *   Objects → Symbols
 *
 * Skin-tone variants and flags are omitted — they don't suit a "feeling" picker.
 */

export const EMOJI_PALETTE: string[] = [
  // ── Smileys & Emotion ──────────────────────────────────────────
  '😀', '😃', '😄', '😁', '😆', '🥹', '😅', '🤣',
  '😂', '🙂', '🙃', '🫠', '😉', '😊', '😇', '🥰',
  '😍', '🤩', '😘', '😗', '☺️', '😚', '😙', '🥲',
  '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭',
  '🫢', '🫣', '🤫', '🤔', '🫡', '🤐', '🤨', '😐',
  '😑', '😶', '🫥', '😶‍🌫️', '😏', '😒', '🙄', '😬',
  '😮‍💨', '🤥', '🫨', '🙂‍↔️', '🙂‍↕️', '😌', '😔', '😪',
  '🤤', '😴', '😷', '🤒', '🤕', '🤢', '🤮', '🥵',
  '🥶', '🥴', '😵', '😵‍💫', '🤯', '🤠', '🥳', '🥸',
  '😎', '🤓', '🧐', '😕', '🫤', '😟', '🙁', '☹️',
  '😮', '😯', '😲', '😳', '🥺', '😦', '😧', '😨',
  '😰', '😥', '😢', '😭', '😱', '😖', '😣', '😞',
  '😓', '😩', '😫', '🥱', '😤', '😡', '😠', '🤬',
  '😈', '👿', '💀', '☠️', '💩', '🤡', '👹', '👺',
  '👻', '👽', '👾', '🤖', '😺', '😸', '😹', '😻',
  '😼', '😽', '🙀', '😿', '😾',
  // ── Smileys & Emotion: Hands / Hearts / Misc ───────────────────
  '🫶', '🤲', '👐', '🙌', '👏', '🤝', '👍', '👎',
  '👊', '✊', '🤛', '🤜', '🤞', '✌️', '🫰', '🤟',
  '🤘', '🫵', '👌', '🤌', '🤏', '👈', '👉', '👆',
  '👇', '☝️', '✋', '🤚', '🖐️', '🖖', '👋', '🤙',
  '💪', '🦾', '🖕', '✍️', '🙏', '💋', '❤️', '🧡',
  '💛', '💚', '💙', '🩵', '💜', '🖤', '🩶', '🤍',
  '🩷', '❤️‍🔥', '❤️‍🩹', '💔', '❣️', '💕', '💞', '💓',
  '💗', '💖', '💘', '💝', '💟', '♥️', '💌', '💢',
  '💥', '💤', '💦', '💨', '🕳️', '💣', '💬', '👁️‍🗨️',
  '🗨️', '🗯️', '💭', '🫧',
  // ── People & Body ──────────────────────────────────────────────
  '👶', '🧒', '👦', '👧', '🧑', '👱', '👨', '🧔',
  '👩', '🧓', '👴', '👵', '🙍', '🙎', '🙅', '🙆',
  '💁', '🙋', '🧏', '🙇', '🤦', '🤷', '👮', '🕵️',
  '💂', '🥷', '👷', '🫅', '🤴', '👸', '👳', '👲',
  '🧕', '🤵', '👰', '🤰', '🫃', '🫄', '🤱', '👼',
  '🎅', '🤶', '🦸', '🦹', '🧙', '🧚', '🧛', '🧜',
  '🧝', '🧞', '🧟', '🧌', '💆', '💇', '🚶', '🧍',
  '🧎', '🏃', '💃', '🕺', '🕴️', '👯', '🧖', '🧗',
  '🤸', '⛹️', '🏋️', '🚴', '🚵', '🤼', '🤽', '🤾',
  '🤺', '⛷️', '🏂', '🏌️', '🏇', '🏄', '🚣', '🏊',
  '🤹', '🧘', '🛀', '🛌', '👀', '👁️', '👅', '👄',
  '🫦', '🧠', '🫀', '🫁', '🦷', '🦴', '👃', '👂',
  '🦶', '🦵', '🦿',
  // ── Animals & Nature ───────────────────────────────────────────
  '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼',
  '🐻‍❄️', '🐨', '🐯', '🦁', '🐮', '🐷', '🐽', '🐸',
  '🐵', '🙈', '🙉', '🙊', '🐒', '🐔', '🐧', '🐦',
  '🐤', '🐣', '🐥', '🦆', '🦅', '🦉', '🦇', '🐺',
  '🐗', '🐴', '🦄', '🐝', '🪱', '🐛', '🦋', '🐌',
  '🐞', '🐜', '🪰', '🪲', '🪳', '🦟', '🦗', '🕷️',
  '🕸️', '🦂', '🐢', '🐍', '🦎', '🦖', '🦕', '🐙',
  '🦑', '🦐', '🦞', '🦀', '🪼', '🐡', '🐠', '🐟',
  '🐬', '🐳', '🐋', '🦈', '🪸', '🐊', '🐅', '🐆',
  '🦓', '🫏', '🦍', '🦧', '🐘', '🦣', '🦛', '🦏',
  '🐪', '🐫', '🦒', '🦘', '🦬', '🐃', '🐂', '🐄',
  '🐎', '🐖', '🐏', '🐑', '🦙', '🐐', '🦌', '🐕',
  '🐩', '🦮', '🐕‍🦺', '🐈', '🐈‍⬛', '🪶', '🐓', '🦃',
  '🦤', '🦚', '🦜', '🦢', '🪿', '🦩', '🐇', '🦝',
  '🦨', '🦡', '🦫', '🦦', '🦥', '🐁', '🐀', '🐿️',
  '🦔', '🐾', '🐉', '🐲', '🌵', '🎄', '🌲', '🌳',
  '🌴', '🪵', '🌱', '🌿', '☘️', '🍀', '🎍', '🪴',
  '🎋', '🍃', '🍂', '🍁', '🪺', '🪹', '🍄', '🐚',
  '🪨', '🌾', '💐', '🌷', '🌹', '🥀', '🌺', '🌸',
  '🌼', '🌻', '🌞', '🌝', '🌛', '🌜', '🌚', '🌕',
  '🌖', '🌗', '🌘', '🌑', '🌒', '🌓', '🌔', '🌙',
  '🌎', '🌍', '🌏', '🪐', '💫', '⭐', '🌟', '✨',
  '⚡', '☄️', '🔥', '🌪️', '🌈', '☀️', '🌤️', '⛅',
  '🌥️', '☁️', '🌦️', '🌧️', '⛈️', '🌩️', '🌨️', '❄️',
  '☃️', '⛄', '🌬️', '💧', '☔', '☂️', '🌊', '🌫️',
  // ── Food & Drink ───────────────────────────────────────────────
  '🍏', '🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇',
  '🍓', '🫐', '🍈', '🍒', '🍑', '🥭', '🍍', '🥥',
  '🥝', '🍅', '🍆', '🥑', '🫛', '🥦', '🥬', '🥒',
  '🌶️', '🫑', '🌽', '🥕', '🫒', '🧄', '🧅', '🫚',
  '🥔', '🍠', '🫘', '🥜', '🌰', '🍞', '🥐', '🥖',
  '🫓', '🥨', '🥯', '🥞', '🧇', '🧀', '🍖', '🍗',
  '🥩', '🥓', '🍔', '🍟', '🍕', '🌭', '🥪', '🌮',
  '🌯', '🫔', '🥙', '🧆', '🥚', '🍳', '🥘', '🍲',
  '🫕', '🥣', '🥗', '🍿', '🧈', '🧂', '🥫', '🍱',
  '🍘', '🍙', '🍚', '🍛', '🍜', '🍝', '🍢', '🍣',
  '🍤', '🍥', '🥮', '🍡', '🥟', '🥠', '🥡', '🦪',
  '🍦', '🍧', '🍨', '🍩', '🍪', '🎂', '🍰', '🧁',
  '🥧', '🍫', '🍬', '🍭', '🍮', '🍯', '🍼', '🥛',
  '☕', '🫖', '🍵', '🍶', '🍾', '🍷', '🍸', '🍹',
  '🍺', '🍻', '🥂', '🥃', '🫗', '🥤', '🧋', '🧃',
  '🧉', '🧊', '🥢', '🍽️', '🍴', '🥄', '🔪', '🫙',
  '🏺',
  // ── Travel & Places ────────────────────────────────────────────
  '🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑',
  '🚒', '🚐', '🛻', '🚚', '🚛', '🚜', '🛵', '🏍️',
  '🛺', '🚲', '🛴', '🛹', '🛼', '🚏', '🛣️', '🛤️',
  '🛞', '⛽', '🚨', '🚥', '🚦', '🛑', '🚧', '⚓',
  '🛟', '⛵', '🛶', '🚤', '🛳️', '⛴️', '🛥️', '🚢',
  '✈️', '🛩️', '🛫', '🛬', '🪂', '💺', '🚁', '🚟',
  '🚠', '🚡', '🛰️', '🚀', '🛸', '🛎️', '🧳', '⌛',
  '⏳', '⌚', '⏰', '⏱️', '⏲️', '🕰️', '🕛', '🗺️',
  '🧭', '🏔️', '⛰️', '🌋', '🗻', '🏕️', '🏖️', '🏜️',
  '🏝️', '🏞️', '🏟️', '🏛️', '🏗️', '🧱', '🛖', '🏘️',
  '🏚️', '🏠', '🏡', '🏢', '🏣', '🏤', '🏥', '🏦',
  '🏨', '🏩', '🏪', '🏫', '🏬', '🏭', '🏯', '🏰',
  '💒', '🗼', '🗽', '⛪', '🕌', '🛕', '🕍', '⛩️',
  '🕋', '⛲', '⛺', '🌁', '🌃', '🏙️', '🌄', '🌅',
  '🌆', '🌇', '🌉', '♨️', '🎠', '🛝', '🎡', '🎢',
  '💈', '🎪',
  // ── Activities ─────────────────────────────────────────────────
  '⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉',
  '🥏', '🎱', '🪀', '🏓', '🏸', '🏒', '🏑', '🥍',
  '🏏', '🪃', '🥅', '⛳', '🪁', '🏹', '🎣', '🤿',
  '🥊', '🥋', '🎽', '🛷', '⛸️', '🥌', '🎿', '🎖️',
  '🏆', '🏅', '🥇', '🥈', '🥉', '🎗️', '🎫', '🎟️',
  '🎭', '🩰', '🎨', '🎬', '🎤', '🎧', '🎼', '🎹',
  '🥁', '🪘', '🎷', '🎺', '🪗', '🎸', '🪕', '🎻',
  '🪈', '🎲', '♟️', '🎯', '🎳', '🎮', '🕹️', '🎰',
  '🧩', '🪩',
  // ── Objects ────────────────────────────────────────────────────
  '👓', '🕶️', '🥽', '🥼', '🦺', '👔', '👕', '👖',
  '🧣', '🧤', '🧥', '🧦', '👗', '👘', '🥻', '🩱',
  '🩲', '🩳', '👙', '👚', '🪭', '👛', '👜', '👝',
  '🛍️', '🎒', '🩴', '👞', '👟', '🥾', '🥿', '👠',
  '👡', '👢', '🪮', '👑', '👒', '🎩', '🎓', '🧢',
  '🪖', '⛑️', '📿', '💄', '💍', '💎', '📱', '📲',
  '💻', '⌨️', '🖥️', '🖨️', '🖱️', '🖲️', '💽', '💾',
  '💿', '📀', '🧮', '🎥', '🎞️', '📽️', '📺', '📷',
  '📸', '📹', '📼', '🔍', '🔎', '🕯️', '💡', '🔦',
  '🏮', '🪔', '📔', '📕', '📖', '📗', '📘', '📙',
  '📚', '📓', '📒', '📃', '📜', '📄', '📰', '🗞️',
  '📑', '🔖', '🏷️', '💰', '🪙', '💴', '💵', '💶',
  '💷', '💸', '💳', '🧾', '💹', '✉️', '📧', '📨',
  '📩', '📤', '📥', '📦', '📫', '📪', '📬', '📭',
  '📮', '🗳️', '✏️', '✒️', '🖋️', '🖊️', '🖌️', '🖍️',
  '📝', '💼', '📁', '📂', '🗂️', '📅', '📆', '🗒️',
  '🗓️', '📇', '📈', '📉', '📊', '📋', '📌', '📍',
  '📎', '🖇️', '📏', '📐', '✂️', '🗃️', '🗄️', '🗑️',
  '🔒', '🔓', '🔏', '🔐', '🔑', '🗝️', '🔨', '🪓',
  '⛏️', '⚒️', '🛠️', '🗡️', '⚔️', '🛡️', '🪚', '🔧',
  '🪛', '🔩', '⚙️', '🗜️', '⚖️', '🦯', '🔗', '⛓️',
  '🪝', '🧰', '🧲', '🪜', '⚗️', '🧪', '🧫', '🧬',
  '🔬', '🔭', '📡', '💉', '🩸', '💊', '🩹', '🩼',
  '🩺', '🩻', '🚪', '🛗', '🪞', '🪟', '🛏️', '🛋️',
  '🪑', '🚽', '🪠', '🚿', '🛁', '🪤', '🪒', '🧴',
  '🧷', '🧹', '🧺', '🧻', '🪣', '🧼', '🪥', '🧽',
  '🧯', '🛒', '🚬', '⚰️', '🪦', '⚱️', '🗿', '🪧',
  '🪬', '🔋', '🪫',
  // ── Symbols ────────────────────────────────────────────────────
  '🏧', '🚮', '🚰', '♿', '🚹', '🚺', '🚻', '🚼',
  '🚾', '🛂', '🛃', '🛄', '🛅', '⚠️', '🚸', '⛔',
  '🚫', '🚳', '🚭', '🚯', '🚱', '🚷', '📵', '🔞',
  '☢️', '☣️', '⬆️', '↗️', '➡️', '↘️', '⬇️', '↙️',
  '⬅️', '↖️', '↕️', '↔️', '↩️', '↪️', '⤴️', '⤵️',
  '🔃', '🔄', '🔙', '🔚', '🔛', '🔜', '🔝', '🔀',
  '🔁', '🔂', '▶️', '⏩', '⏭️', '⏯️', '◀️', '⏪',
  '⏮️', '🔼', '⏫', '🔽', '⏬', '⏸️', '⏹️', '⏺️',
  '⏏️', '🎦', '🔅', '🔆', '📶', '🛜', '📳', '📴',
  '♀️', '♂️', '⚧️', '✖️', '➕', '➖', '➗', '🟰',
  '♾️', '‼️', '⁉️', '❓', '❔', '❕', '❗', '〰️',
  '💱', '💲', '⚕️', '♻️', '⚜️', '🔱', '📛', '🔰',
  '⭕', '✅', '☑️', '✔️', '❌', '❎', '➰', '➿',
  '〽️', '✳️', '✴️', '❇️', '©️', '®️', '™️', '#️⃣',
  '*️⃣', '0️⃣', '1️⃣', '2️⃣', '3️⃣', '4️⃣', '5️⃣', '6️⃣',
  '7️⃣', '8️⃣', '9️⃣', '🔟', '🔠', '🔡', '🔢', '🔣',
  '🔤', '🆎', '🅰️', '🅱️', '🆑', '🆒', '🆓', 'ℹ️',
  '🆔', 'Ⓜ️', '🆕', '🆖', '🅾️', '🆗', '🅿️', '🆘',
  '🆙', '🆚', '🈁', '🈂️', '🔴', '🟠', '🟡', '🟢',
  '🔵', '🟣', '🟤', '⚫', '⚪', '🟥', '🟧', '🟨',
  '🟩', '🟦', '🟪', '🟫', '⬛', '⬜', '◼️', '◻️',
  '◾', '◽', '▪️', '▫️', '🔶', '🔷', '🔸', '🔹',
  '🔺', '🔻', '💠', '🔘', '🔳', '🔲', '🏁', '🚩',
  '🎌', '🏴', '🏳️', '🏳️‍🌈', '🏳️‍⚧️', '🏴‍☠️',

]

/**
 * Keyword search index — not every emoji needs an entry.
 * Only the ones people are likely to search for by word.
 */
export const EMOJI_KEYWORDS: Record<string, string[]> = {
  // ── Smileys ────────────────────────────────────────────────────
  '😀': ['happy', 'grin', 'smile'],
  '😃': ['happy', 'smile', 'joy'],
  '😄': ['happy', 'smile', 'laugh'],
  '😁': ['grin', 'happy', 'beam'],
  '😆': ['laugh', 'haha', 'lol'],
  '🥹': ['touched', 'moved', 'grateful', 'aww'],
  '😅': ['nervous', 'sweat', 'awkward', 'phew'],
  '🤣': ['lol', 'rofl', 'laugh', 'haha'],
  '😂': ['crying', 'laugh', 'tears', 'lol'],
  '🙂': ['smile', 'ok', 'fine', 'pleasant'],
  '🙃': ['sarcastic', 'upside', 'ironic'],
  '🫠': ['melting', 'melt', 'dissolve', 'overwhelmed'],
  '😉': ['wink', 'flirty', 'hint'],
  '😊': ['happy', 'smile', 'glad', 'blush'],
  '😇': ['angel', 'innocent', 'good', 'halo'],
  '🥰': ['love', 'adore', 'hearts', 'affection'],
  '😍': ['love', 'heart eyes', 'crush', 'adore'],
  '🤩': ['excited', 'star', 'wow', 'amazing', 'starstruck'],
  '😘': ['kiss', 'love', 'flirty', 'muah'],
  '😗': ['kiss', 'whistle', 'smooch'],
  '☺️': ['blush', 'happy', 'content', 'warm'],
  '😚': ['kiss', 'blush', 'sweet'],
  '😙': ['whistle', 'kiss', 'happy'],
  '🥲': ['happy', 'cry', 'bittersweet', 'proud'],
  '😋': ['yummy', 'tasty', 'hungry', 'delicious'],
  '😛': ['tongue', 'silly', 'playful'],
  '😜': ['wink', 'tongue', 'silly', 'goofy'],
  '🤪': ['crazy', 'wild', 'silly', 'zany'],
  '😝': ['tongue', 'squint', 'playful', 'bleh'],
  '🤑': ['money', 'rich', 'greedy', 'dollar'],
  '🤗': ['hug', 'warm', 'open', 'embrace'],
  '🤭': ['giggle', 'oops', 'tee hee', 'shy'],
  '🫢': ['gasp', 'oops', 'surprised', 'shock'],
  '🫣': ['peeking', 'shy', 'nervous', 'cant look'],
  '🤫': ['secret', 'quiet', 'shh', 'hush'],
  '🤔': ['thinking', 'hmm', 'wonder', 'curious'],
  '🫡': ['salute', 'respect', 'yes sir', 'roger'],
  '🤐': ['zip', 'quiet', 'sealed', 'mum'],
  '🤨': ['skeptical', 'suspicious', 'doubt', 'eyebrow'],
  '😐': ['neutral', 'meh', 'blank', 'straight face'],
  '😑': ['flat', 'annoyed', 'done', 'expressionless'],
  '😶': ['blank', 'silent', 'mute', 'speechless'],
  '🫥': ['dotted', 'invisible', 'empty', 'hidden'],
  '😶‍🌫️': ['foggy', 'cloudy', 'haze', 'confused'],
  '😏': ['smirk', 'sly', 'flirty', 'smug'],
  '😒': ['unamused', 'meh', 'side eye', 'annoyed'],
  '🙄': ['eye roll', 'whatever', 'annoyed', 'ugh'],
  '😬': ['cringe', 'yikes', 'oops', 'grimace'],
  '😮‍💨': ['sigh', 'exhale', 'relief', 'tired'],
  '🤥': ['lie', 'pinocchio', 'fib'],
  '🫨': ['shaking', 'vibrating', 'anxious', 'shook'],
  '🙂‍↔️': ['shaking head', 'no'],
  '🙂‍↕️': ['nodding', 'yes'],
  '😌': ['calm', 'relieved', 'peace', 'content'],
  '😔': ['sad', 'pensive', 'down', 'disappointed'],
  '😪': ['sleepy', 'tired', 'bored'],
  '🤤': ['drool', 'hungry', 'want', 'craving'],
  '😴': ['sleep', 'zzz', 'tired', 'snore'],
  '😷': ['sick', 'mask', 'ill', 'cold'],
  '🤒': ['sick', 'fever', 'ill', 'temperature'],
  '🤕': ['hurt', 'injured', 'bandage', 'headache'],
  '🤢': ['nauseous', 'sick', 'gross', 'queasy'],
  '🤮': ['vomit', 'sick', 'gross', 'throw up'],
  '🥵': ['hot', 'sweating', 'heat', 'thirsty'],
  '🥶': ['cold', 'freezing', 'ice', 'shiver'],
  '🥴': ['woozy', 'drunk', 'loopy', 'dizzy'],
  '😵': ['dizzy', 'dead', 'knocked out'],
  '😵‍💫': ['dizzy', 'confused', 'spiral', 'disoriented'],
  '🤯': ['mind blown', 'shocked', 'wow', 'exploding'],
  '🤠': ['cowboy', 'yeehaw', 'country', 'howdy'],
  '🥳': ['party', 'celebrate', 'fun', 'birthday'],
  '🥸': ['disguise', 'incognito', 'sneaky', 'glasses'],
  '😎': ['cool', 'chill', 'confident', 'sunglasses'],
  '🤓': ['nerd', 'smart', 'studious', 'geek'],
  '🧐': ['monocle', 'inspect', 'curious', 'examine'],
  '😕': ['confused', 'unsure', 'puzzled'],
  '🫤': ['skeptical', 'meh', 'diagonal mouth'],
  '😟': ['worried', 'concerned', 'anxious'],
  '🙁': ['sad', 'frown', 'unhappy', 'down'],
  '☹️': ['frown', 'sad', 'unhappy'],
  '😮': ['surprised', 'oh', 'wow'],
  '😯': ['surprised', 'hushed', 'stunned'],
  '😲': ['astonished', 'shocked', 'wow'],
  '😳': ['flushed', 'embarrassed', 'surprised', 'blush'],
  '🥺': ['pleading', 'puppy eyes', 'please', 'begging'],
  '😦': ['frown', 'worried'],
  '😧': ['anguished', 'worried'],
  '😨': ['fearful', 'scared', 'afraid'],
  '😰': ['anxious', 'worried', 'nervous', 'sweat'],
  '😥': ['sad', 'relieved', 'disappointed'],
  '😢': ['sad', 'cry', 'tear'],
  '😭': ['crying', 'sad', 'tears', 'sobbing', 'bawling'],
  '😱': ['scream', 'scared', 'shock', 'horror'],
  '😖': ['confounded', 'frustrated'],
  '😣': ['persevere', 'struggling', 'endure'],
  '😞': ['disappointed', 'sad', 'let down'],
  '😓': ['downcast', 'sweat', 'hard work'],
  '😩': ['weary', 'tired', 'exhausted', 'done'],
  '😫': ['tired', 'exhausted', 'fed up'],
  '🥱': ['tired', 'sleepy', 'bored', 'yawn'],
  '😤': ['angry', 'frustrated', 'mad', 'huff', 'steam'],
  '😡': ['angry', 'mad', 'rage', 'furious'],
  '😠': ['angry', 'mad', 'grr', 'grumpy'],
  '🤬': ['swear', 'angry', 'furious', 'cursing'],
  '😈': ['devious', 'mischief', 'evil', 'naughty'],
  '👿': ['angry', 'devil', 'evil', 'imp'],
  '💀': ['dead', 'skull', 'dying', 'lol'],
  '☠️': ['skull', 'crossbones', 'danger', 'death'],
  '💩': ['poop', 'crap', 'gross', 'shit'],
  '🤡': ['clown', 'silly', 'fool', 'joke'],
  '👹': ['ogre', 'monster', 'scary'],
  '👺': ['goblin', 'monster', 'tengu'],
  '👻': ['ghost', 'spooky', 'boo', 'halloween'],
  '👽': ['alien', 'space', 'ufo', 'extraterrestrial'],
  '👾': ['alien', 'game', 'monster', 'space invader'],
  '🤖': ['robot', 'bot', 'machine', 'ai'],

  // ── Hands & Gestures ───────────────────────────────────────────
  '🫶': ['heart hands', 'love', 'care'],
  '👐': ['open hands', 'jazz hands'],
  '🙌': ['raise', 'celebrate', 'hooray', 'yay'],
  '👏': ['clap', 'bravo', 'applause', 'congrats'],
  '🤝': ['handshake', 'deal', 'agree', 'partnership'],
  '👍': ['thumbs up', 'yes', 'good', 'ok', 'like'],
  '👎': ['thumbs down', 'no', 'bad', 'dislike'],
  '👊': ['punch', 'fist bump', 'power'],
  '✊': ['fist', 'solidarity', 'fight', 'power'],
  '🤞': ['fingers crossed', 'luck', 'hope'],
  '✌️': ['peace', 'victory', 'two'],
  '🫰': ['pinch', 'money', 'snap'],
  '🤟': ['love you', 'rock', 'sign language'],
  '🤘': ['rock', 'metal', 'horns'],
  '🫵': ['point', 'you', 'pointing'],
  '👌': ['ok', 'perfect', 'nice', 'fine'],
  '🤌': ['chef kiss', 'perfect', 'italian', 'pinched'],
  '🤏': ['tiny', 'small', 'little', 'pinch'],
  '👋': ['wave', 'hi', 'hello', 'bye'],
  '🤙': ['call', 'hang loose', 'shaka'],
  '💪': ['strong', 'power', 'muscle', 'gym', 'flex'],
  '🦾': ['robot arm', 'strong', 'mechanical', 'prosthetic'],
  '🙏': ['pray', 'hope', 'please', 'grateful', 'namaste', 'thank'],
  '🤷': ['shrug', 'idk', 'whatever', 'dunno'],
  '🤦': ['facepalm', 'smh', 'disappointed', 'doh'],

  // ── Hearts ─────────────────────────────────────────────────────
  '❤️': ['love', 'heart', 'care', 'red'],
  '🧡': ['orange', 'heart', 'love'],
  '💛': ['yellow', 'heart', 'love', 'friendship'],
  '💚': ['green', 'heart', 'love'],
  '💙': ['blue', 'heart', 'love'],
  '🩵': ['light blue', 'heart', 'love'],
  '💜': ['purple', 'heart', 'love'],
  '🖤': ['black', 'heart', 'dark', 'goth'],
  '🩶': ['grey', 'heart'],
  '🤍': ['white', 'heart', 'pure'],
  '🩷': ['pink', 'heart', 'love'],
  '❤️‍🔥': ['heart fire', 'passion', 'burning love'],
  '❤️‍🩹': ['mending', 'healing', 'recovering'],
  '💔': ['broken', 'heart', 'sad', 'heartbreak'],
  '💕': ['hearts', 'love', 'two'],
  '💞': ['revolving', 'hearts', 'love'],
  '💓': ['heartbeat', 'love', 'alive'],
  '💗': ['growing', 'heart', 'love'],
  '💖': ['sparkle', 'heart', 'love'],
  '💘': ['cupid', 'arrow', 'heart', 'love'],
  '💝': ['gift', 'heart', 'love'],
  '✨': ['sparkle', 'magic', 'new', 'clean', 'shine'],
  '⭐': ['star', 'gold', 'favorite'],
  '🌟': ['glow', 'star', 'shine', 'bright'],
  '💫': ['dizzy', 'star', 'magic', 'shooting'],
  '⚡': ['energy', 'electric', 'fast', 'bolt', 'lightning'],
  '🔥': ['fire', 'hot', 'lit', 'productive', 'flame'],
  '💥': ['boom', 'collision', 'impact', 'pow'],
  '💤': ['sleep', 'zzz', 'tired', 'nap'],
  '💭': ['thought', 'thinking', 'bubble'],
  '💬': ['speech', 'talk', 'chat', 'comment'],
  '🫧': ['bubbles', 'light', 'airy', 'float', 'clean'],

  // ── Body ───────────────────────────────────────────────────────
  '👀': ['eyes', 'look', 'watching', 'curious', 'stare'],
  '👁️': ['eye', 'see', 'watch', 'vision'],
  '👅': ['tongue', 'taste', 'lick'],
  '🧠': ['brain', 'think', 'smart', 'mental', 'mind'],
  '🫀': ['heart', 'alive', 'pulse', 'anatomical'],
  '🦷': ['tooth', 'dentist'],
  '🦴': ['bone', 'skeleton'],

  // ── Animals ────────────────────────────────────────────────────
  '🐶': ['dog', 'puppy', 'pet', 'cute'],
  '🐱': ['cat', 'kitty', 'pet', 'cute'],
  '🐭': ['mouse', 'small', 'cute'],
  '🐹': ['hamster', 'cute', 'pet'],
  '🐰': ['bunny', 'rabbit', 'cute', 'easter'],
  '🦊': ['fox', 'clever', 'sly'],
  '🐻': ['bear', 'teddy'],
  '🐼': ['panda', 'cute', 'bear'],
  '🐻‍❄️': ['polar bear', 'cold', 'arctic'],
  '🐨': ['koala', 'cute', 'sleep'],
  '🐯': ['tiger', 'fierce', 'cat'],
  '🦁': ['lion', 'king', 'brave', 'fierce'],
  '🐮': ['cow', 'moo'],
  '🐷': ['pig', 'oink', 'cute'],
  '🐸': ['frog', 'ribbit', 'kermit', 'tea'],
  '🐵': ['monkey', 'ape'],
  '🙈': ['see no evil', 'shy', 'hide', 'embarrassed'],
  '🙉': ['hear no evil', 'ignore'],
  '🙊': ['speak no evil', 'oops', 'secret'],
  '🐔': ['chicken', 'hen', 'cluck'],
  '🐧': ['penguin', 'cold', 'cute', 'waddle'],
  '🐦': ['bird', 'tweet', 'chirp'],
  '🦆': ['duck', 'quack'],
  '🦅': ['eagle', 'freedom', 'soar'],
  '🦉': ['owl', 'wise', 'night'],
  '🦇': ['bat', 'dark', 'vampire', 'night'],
  '🐺': ['wolf', 'howl'],
  '🐴': ['horse', 'gallop'],
  '🦄': ['unicorn', 'magic', 'fantasy', 'rainbow'],
  '🐝': ['bee', 'busy', 'buzz', 'honey'],
  '🦋': ['butterfly', 'change', 'nervous', 'flutter', 'transform'],
  '🐌': ['snail', 'slow'],
  '🐞': ['ladybug', 'lucky'],
  '🐢': ['turtle', 'slow', 'steady'],
  '🐍': ['snake', 'sneaky'],
  '🐙': ['octopus', 'tentacle'],
  '🐬': ['dolphin', 'ocean', 'swim', 'playful'],
  '🐳': ['whale', 'ocean', 'big', 'spray'],
  '🦈': ['shark', 'danger', 'ocean'],
  '🐊': ['crocodile', 'alligator', 'danger'],
  '🐘': ['elephant', 'big', 'memory'],
  '🦒': ['giraffe', 'tall'],
  '🐕': ['dog', 'pet', 'faithful'],
  '🐈': ['cat', 'pet'],
  '🐈‍⬛': ['black cat', 'unlucky', 'cat'],
  '🐉': ['dragon', 'fire', 'power', 'fantasy'],
  '🕊️': ['peace', 'dove', 'calm', 'free'],

  // ── Nature & Weather ───────────────────────────────────────────
  '🌵': ['cactus', 'desert', 'dry'],
  '🎄': ['christmas', 'tree', 'holiday'],
  '🌲': ['tree', 'evergreen', 'forest', 'nature'],
  '🌳': ['tree', 'deciduous', 'nature', 'park'],
  '🌴': ['palm', 'tropical', 'beach', 'vacation'],
  '🌱': ['seedling', 'grow', 'new', 'sprout', 'growth'],
  '🌿': ['herb', 'nature', 'green', 'chill', 'plant'],
  '☘️': ['shamrock', 'irish', 'lucky'],
  '🍀': ['clover', 'lucky', 'luck', 'four leaf'],
  '🍃': ['leaf', 'nature', 'zen', 'breath', 'wind'],
  '🍂': ['fallen', 'leaf', 'autumn', 'fall'],
  '🍁': ['maple', 'leaf', 'fall', 'canada'],
  '🍄': ['mushroom', 'fungus', 'magic'],
  '🌹': ['rose', 'flower', 'love', 'romantic'],
  '🌸': ['blossom', 'spring', 'flower', 'pretty', 'cherry'],
  '🌼': ['flower', 'blossom', 'daisy'],
  '🌻': ['sunflower', 'happy', 'bright', 'sun'],
  '🌞': ['sun', 'face', 'bright', 'happy'],
  '🌙': ['moon', 'night', 'sleep', 'late', 'crescent'],
  '🌎': ['earth', 'world', 'globe', 'planet'],
  '🪐': ['planet', 'saturn', 'space', 'ring'],
  '☀️': ['sun', 'sunny', 'bright', 'warm', 'day'],
  '🌤️': ['partly sunny', 'mild', 'nice'],
  '⛅': ['cloudy', 'partly', 'overcast'],
  '☁️': ['cloud', 'overcast', 'grey'],
  '🌧️': ['rain', 'sad', 'gloomy', 'grey', 'rainy'],
  '⛈️': ['storm', 'intense', 'chaos', 'thunder', 'lightning'],
  '🌩️': ['lightning', 'storm', 'thunder'],
  '🌨️': ['snow', 'cold', 'winter'],
  '❄️': ['snowflake', 'cold', 'ice', 'winter', 'frozen'],
  '🌬️': ['wind', 'blow', 'breeze'],
  '💧': ['drop', 'water', 'tear', 'sweat'],
  '☔': ['rain', 'umbrella', 'wet'],
  '🌊': ['wave', 'ocean', 'flow', 'water', 'surf'],
  '🌫️': ['fog', 'mist', 'hazy'],
  '🌈': ['rainbow', 'hope', 'bright', 'color', 'pride'],
  '🌪️': ['tornado', 'chaos', 'whirlwind', 'storm'],
  '🌀': ['spiral', 'scattered', 'swirl', 'cyclone', 'dizzy'],

  // ── Food & Drink ───────────────────────────────────────────────
  '🍎': ['apple', 'fruit', 'red', 'healthy'],
  '🍌': ['banana', 'fruit', 'yellow'],
  '🍉': ['watermelon', 'summer', 'fruit'],
  '🍇': ['grapes', 'wine', 'fruit'],
  '🍓': ['strawberry', 'berry', 'fruit', 'sweet'],
  '🫐': ['blueberry', 'berry', 'fruit'],
  '🍒': ['cherry', 'fruit', 'red'],
  '🍑': ['peach', 'fruit', 'butt'],
  '🥑': ['avocado', 'guac', 'healthy', 'millennial'],
  '🌶️': ['pepper', 'hot', 'spicy'],
  '🍔': ['burger', 'hamburger', 'food', 'fast food'],
  '🍟': ['fries', 'french fries', 'fast food'],
  '🍕': ['pizza', 'food', 'slice'],
  '🌮': ['taco', 'mexican', 'food'],
  '🍳': ['egg', 'cooking', 'breakfast', 'frying'],
  '🍿': ['popcorn', 'movie', 'snack'],
  '🍩': ['donut', 'sweet', 'treat', 'doughnut'],
  '🍪': ['cookie', 'sweet', 'treat', 'biscuit'],
  '🎂': ['cake', 'birthday', 'celebrate'],
  '🍰': ['cake', 'treat', 'sweet', 'slice'],
  '🍫': ['chocolate', 'sweet', 'candy'],
  '🍬': ['candy', 'sweet'],
  '🍭': ['lollipop', 'candy', 'sweet'],
  '🍦': ['ice cream', 'dessert', 'sweet', 'cold'],
  '☕': ['coffee', 'morning', 'caffeine', 'cozy', 'hot'],
  '🫖': ['teapot', 'tea', 'brew'],
  '🍵': ['tea', 'calm', 'warm', 'matcha', 'green tea'],
  '🍶': ['sake', 'japanese', 'alcohol'],
  '🍾': ['champagne', 'celebrate', 'pop', 'party'],
  '🍷': ['wine', 'relax', 'evening', 'glass'],
  '🍸': ['cocktail', 'martini', 'drink'],
  '🍹': ['tropical', 'drink', 'cocktail', 'vacation'],
  '🍺': ['beer', 'cheers', 'chill', 'pub'],
  '🍻': ['cheers', 'beer', 'celebrate', 'toast'],
  '🥂': ['champagne', 'toast', 'celebrate', 'cheers'],
  '🥃': ['whiskey', 'drink', 'tumbler'],
  '🫗': ['pour', 'empty', 'spill', 'drain'],
  '🥤': ['soda', 'drink', 'straw'],
  '🧋': ['boba', 'bubble tea', 'milk tea'],
  '🧃': ['juice', 'box', 'drink'],
  '🧊': ['ice', 'cold', 'frozen', 'cool', 'cube'],

  // ── Activities ─────────────────────────────────────────────────
  '⚽': ['soccer', 'football', 'sport'],
  '🏀': ['basketball', 'sport', 'ball'],
  '🏈': ['football', 'american', 'sport'],
  '🎾': ['tennis', 'sport', 'ball'],
  '🎱': ['pool', 'billiards', 'eight ball'],
  '🎳': ['bowling', 'strike'],
  '🎯': ['target', 'focus', 'goal', 'aim', 'bullseye', 'dart'],
  '🎮': ['game', 'gaming', 'controller', 'play', 'video game'],
  '🕹️': ['joystick', 'arcade', 'game', 'retro'],
  '🎰': ['slot', 'gamble', 'casino', 'jackpot'],
  '🧩': ['puzzle', 'piece', 'solve', 'jigsaw'],
  '🪩': ['disco', 'party', 'dance', 'fun', 'mirror ball'],
  '🎭': ['drama', 'masks', 'acting', 'dual', 'theater'],
  '🎨': ['art', 'paint', 'palette', 'creative'],
  '🎬': ['movie', 'film', 'action', 'camera'],
  '🎤': ['microphone', 'sing', 'karaoke', 'music'],
  '🎧': ['headphones', 'music', 'listen', 'audio'],
  '🎼': ['music', 'score', 'notes'],
  '🎹': ['piano', 'keyboard', 'music'],
  '🥁': ['drum', 'beat', 'music', 'rhythm'],
  '🎷': ['saxophone', 'jazz', 'music'],
  '🎸': ['guitar', 'rock', 'music'],
  '🎻': ['violin', 'classical', 'music', 'fiddle'],
  '🎲': ['dice', 'gamble', 'random', 'chance', 'game'],
  '🏆': ['trophy', 'win', 'champion', 'award', 'first'],
  '🥇': ['gold', 'medal', 'first', 'winner'],
  '🥈': ['silver', 'medal', 'second'],
  '🥉': ['bronze', 'medal', 'third'],

  // ── Objects ────────────────────────────────────────────────────
  '👑': ['crown', 'king', 'queen', 'royal'],
  '💎': ['diamond', 'gem', 'precious', 'shine'],
  '📱': ['phone', 'screen', 'scroll', 'mobile'],
  '💻': ['computer', 'laptop', 'work', 'code'],
  '⌨️': ['keyboard', 'type', 'code'],
  '🖥️': ['desktop', 'computer', 'monitor'],
  '💡': ['idea', 'light', 'bulb', 'bright', 'think'],
  '🔦': ['flashlight', 'torch', 'light', 'search'],
  '📚': ['books', 'read', 'study', 'learn', 'library'],
  '📖': ['book', 'read', 'open', 'story'],
  '📝': ['note', 'write', 'memo', 'pencil'],
  '💼': ['briefcase', 'work', 'business', 'job'],
  '📊': ['chart', 'graph', 'data', 'stats'],
  '📈': ['chart', 'up', 'growth', 'trending'],
  '📉': ['chart', 'down', 'decline', 'falling'],
  '📅': ['calendar', 'date', 'schedule'],
  '📌': ['pin', 'push pin', 'location', 'mark'],
  '📎': ['paperclip', 'attach', 'office'],
  '✂️': ['scissors', 'cut'],
  '🔑': ['key', 'lock', 'access', 'password'],
  '🗝️': ['old key', 'vintage', 'unlock', 'secret'],
  '🔒': ['lock', 'secure', 'private', 'closed'],
  '🔓': ['unlock', 'open', 'access'],
  '🔨': ['hammer', 'build', 'tool', 'construct'],
  '🛠️': ['tools', 'fix', 'repair', 'build'],
  '⚙️': ['gear', 'settings', 'cog', 'mechanical'],
  '🧲': ['magnet', 'attract', 'pull'],
  '⚗️': ['alchemy', 'chemistry', 'experiment'],
  '🧪': ['test tube', 'science', 'experiment', 'lab'],
  '🧬': ['dna', 'genetics', 'science', 'biology'],
  '🔬': ['microscope', 'science', 'research', 'examine'],
  '🔭': ['telescope', 'space', 'astronomy', 'look'],
  '📡': ['satellite', 'signal', 'broadcast'],
  '💉': ['syringe', 'vaccine', 'shot', 'medical'],
  '💊': ['pill', 'medicine', 'drug'],
  '🩹': ['bandaid', 'band-aid', 'heal', 'fix'],
  '🩺': ['stethoscope', 'doctor', 'medical'],
  '🚪': ['door', 'entrance', 'exit', 'open'],
  '🛏️': ['bed', 'sleep', 'rest'],
  '🛋️': ['couch', 'sofa', 'relax', 'comfort'],
  '🧸': ['teddy', 'bear', 'comfort', 'soft', 'cozy'],
  '🧯': ['extinguisher', 'fire', 'emergency'],
  '🛒': ['cart', 'shopping', 'buy', 'grocery'],
  '🔋': ['battery', 'charged', 'full', 'energy', 'power'],
  '🪫': ['low battery', 'drained', 'empty', 'dying'],
  '💣': ['bomb', 'intense', 'drop', 'explosive'],
  '🧨': ['explosive', 'tense', 'boom', 'firecracker'],

  // ── Symbols ────────────────────────────────────────────────────
  '⚠️': ['warning', 'caution', 'alert', 'danger'],
  '⛔': ['stop', 'no entry', 'forbidden'],
  '🚫': ['no', 'forbidden', 'prohibited', 'stop'],
  '🔁': ['loop', 'stuck', 'repeat', 'cycle', 'replay'],
  '🔂': ['repeat one', 'single', 'loop'],
  '🔀': ['shuffle', 'random', 'mix'],
  '▶️': ['play', 'start', 'go', 'forward'],
  '⏸️': ['pause', 'break', 'stop', 'wait'],
  '⏹️': ['stop', 'end', 'halt'],
  '♾️': ['infinity', 'forever', 'endless', 'loop'],
  '❓': ['question', 'what', 'why', 'how'],
  '❗': ['exclamation', 'important', 'alert', 'urgent'],
  '♻️': ['recycle', 'green', 'environment', 'renew'],
  '✅': ['check', 'done', 'complete', 'yes', 'approved'],
  '❌': ['no', 'wrong', 'delete', 'remove', 'x'],
  '🔴': ['red', 'circle', 'stop', 'dot'],
  '🟠': ['orange', 'circle', 'dot'],
  '🟡': ['yellow', 'circle', 'dot'],
  '🟢': ['green', 'circle', 'go', 'dot'],
  '🔵': ['blue', 'circle', 'dot'],
  '🟣': ['purple', 'circle', 'dot'],
  '⚫': ['black', 'circle', 'dot'],
  '⚪': ['white', 'circle', 'dot'],
  '🏳️‍🌈': ['pride', 'rainbow', 'lgbtq', 'flag'],
  '🏴‍☠️': ['pirate', 'flag', 'skull', 'jolly roger'],
  '🎶': ['music', 'song', 'vibes', 'notes', 'singing'],
}
