type ToastTemplate = string | ((time: string) => string)

export const CREATE_TOASTS: ToastTemplate[] = [
  (t) => `Logged · ${t}.Now go do the thing.`,
  'Clear. Time to do the thing.',
  (t) => `Stamped · ${t}. Go do the thing.`,
  'Now captured. Next: do the thing.',
  (t) => `Locked in · ${t}. Time to move.`,
  'Saved. Tiny step, big momentum.',
  'Good. One line. One move.',
  (t) => `Noted · ${t}. Keep it simple.`,
  'You named it. Now do it.',
  "Moment logged. Don't overthink it.",
  (t) => `Clean entry · ${t}. Action time.`,
  'There it is. Go do the thing.',
]

export const COMPLETE_TOASTS: ToastTemplate[] = [
  'You did the thing. Nice.',
  (t) => `Did the thing · ${t}.`,
  (t) => `Thing done · ${t}. Onward.`,
  "Checked. That's a real win.",
  'Done. Small proof you move.',
  'You did it. Log closed.',
  (t) => `Complete · ${t}. Keep going.`,
  "That's the thing. You did it.",
  'Checked off. Calm progress.',
  'Finished. Next tiny step?',
  'Did the thing. Quietly proud.',
  (t) => `Done · ${t}. Momentum kept.`,
]

export const EDIT_TOASTS: ToastTemplate[] = [
  (t) => `Edit saved · ${t}. Back to the thing.`,
  'Rewritten. Keep moving.',
  (t) => `Tightened up · ${t}. Proceed.`,
  'Updated. No extra drama.',
  'Adjusted. Now do the thing.',
  'Cleaned. One line closer.',
  (t) => `Saved your tweak · ${t}. Go.`,
  'Sharpened. Action fits.',
  'Fixed. Momentum intact.',
  (t) => `Edit locked in · ${t}. Onward.`,
  'Polished. Next tiny step.',
  "Yep. That's the right words.",
]

export const UNCOMPLETE_TOASTS: ToastTemplate[] = [
  (t) => `Back in play · ${t}. Do the thing.`,
  'Undo logged. Keep moving.',
  'Not done yet. That\'s fine. Next tiny step.',
  (t) => `Reopened · ${t}. One move.`,
  'Check reversed. Momentum intact.',
  'Returned to the thing. Proceed.',
  'Un-did it. Now do it (again).',
  'Put it back on the board. Action time.',
  (t) => `Rolling it back · ${t}. No drama.`,
  'Unfinished on purpose. Choose the next pebble.',
  "Checkbox unticked. You're still the kind of person who moves.",
  'Reset. Clean slate. One small proof.',
]

export const FEELING_TOASTS: Record<string, ToastTemplate[]> = {
  '😌': [
    'Calm logged. Smooth seas, small steps.',
    'Easy breath. Soft start, real move.',
    'Stillness noted. Now: one gentle action.',
    'Settled. Keep it simple, keep it kind.',
    'Still water. One line, one oar stroke.',
    'Calm is a compass. Follow the next tiny step.',
    'Collected. No rush, just forward.',
    'Steady hands. Tiny step.',
    'Quiet mind, clear move.',
    'Peaceful mode. Proceed softly.',
    'Grounded. Action fits the moment.',
    (t) => `Calm checked in · ${t}. Keep it light.`,
  ],
  '⚡': [
    'Energy logged. Aim it like a laser.',
    "Spark's up. Strike while it's simple.",
    'Charge on. Next tiny step, little zap.',
    'Good juice. Squeeze a win.',
    'Let it rip. Then let it ship.',
    'Momentum spotted. Catch it.',
    'Bright mode. Build a little something.',
    'Hot start. Clean finish.',
    'Ready. Tip the first domino.',
    (t) => `Energized · ${t}. Use the boost.`,
    'Wired (in a good way). Ship one step.',
    'Go mode. Keep it tidy.',
  ],
  '😊': [
    'Good logged. Pocket that.',
    'Feeling good. Spend it on the thing.',
    'Nice. One more small win, why not.',
    'Solid mood. Solid move.',
    'Good enough to go (and you are).',
    'Bright day. Tiny step, big proof.',
    'Yep. Action fits.',
    'Lightness logged. Lift one task.',
    (t) => `Good · ${t}. Keep it rolling.`,
    'Smile noted. Make it real.',
    'Clean vibe. Clean follow-through.',
    "You've got this. Easy does it.",
  ],
  '🎯': [
    'Locked on. Bullseye energy.',
    'Focus set. One tiny step. No extras.',
    'Tunnel vision, but make it useful.',
    'Aim true. Send it.',
    'Distractions out. One move in.',
    'Dialed in. Keep it narrow, keep it kind.',
    'Sharp. Put it on the page.',
    'Zero fluff. Maximum forward.',
    (t) => `Focus captured · ${t}. Go time.`,
    'On task. No bargaining. Just doing.',
    'Pointed. Make it real.',
    'Target acquired. Gentle execution.',
  ],
  '😶‍🌫️': [
    'Foggy logged. Find the next lamppost.',
    'Low visibility. Take the next tiny step.',
    'Roll the fog back with one small move.',
    (t) => `Fog bank · ${t}. One step forward.`,
    'Cut through it: write one sentence.',
    "Can't see the whole road? Just the next ten feet.",
    'Mist happens. Do the smallest version.',
    'Condense it to one checkbox.',
    'Clear a patch: open the file.',
    'Follow the sound: one click, then one line.',
    (t) => `Foglift · ${t}. Micro-step time.`,
    "Eyes forward. Small move. You're back.",
  ],
  '🌀': [
    'Scattered logged. Pick one thread.',
    'Too many tabs in the brain. Close to one.',
    (t) => `Scattered · ${t}. One target, one move.`,
    'Bring it in. Next tiny step.',
    'One tab. One task. One you.',
    'Gather the confetti: write the next action.',
    'Scatter to single: do the thing.',
    'One line to anchor you.',
    'Zoom in. Execute one move.',
    'Scattered, but capable. Choose one.',
    'Make a small decision. Then act.',
    'Narrow the beam. Shine it on the thing.',
  ],
  '🔁': [
    'Stuck logged. Nudge, not shove.',
    'Looping again? Break it with one tiny move.',
    'Stuck is okay. Try the smallest unlock.',
    'Gears grinding. One tooth forward.',
    'Stalled out. Tap the starter step.',
    (t) => `Stuck · ${t}. Shrink it until it moves.`,
    'Frozen cursor. Type one honest line.',
    'Brain buffering. Click one real thing.',
    'Caught in the loop. Change one pixel.',
    'Held in place. Wiggle one finger of the task.',
    'Stuck, not broken. Micro-step anyway.',
    'Even a half move still counts as movement.',
  ],
  '😔': [
    'Down logged. Still here. Still counts.',
    "Low day. One tiny step. That's it.",
    'Soft mode. Minimum viable move.',
    'Heavy feelings. Gentle action.',
    'Not great. Still moving, quietly.',
    (t) => `Down · ${t}. One small proof is enough.`,
    'Here, softly. Next step: simple.',
    'No pep required. Just one nudge.',
    'Okay. Do the smallest true thing.',
    'Low battery, low bar. Start anyway.',
    'A little dim. One line still shines.',
    'Down noted. Progress can whisper.',
  ],
  '😰': [
    'Anxious logged. Tiny step, big relief.',
    'Spinning? Make it one small circle.',
    'Nerves noted. One move, then breathe.',
    (t) => `Anxious · ${t}. Keep it simple, keep it safe.`,
    'Too loud in there? One quiet action.',
    'Fear can ride along. You still drive.',
    'Worry logged. Next step only.',
    'Tight chest, tiny task. Works.',
    'No catastrophes, just one checkbox.',
    'Ground it: write the next line.',
    'Anxious, not stuck. Small move.',
    'Okay. One step. Then check in.',
  ],
  '😩': [
    'Overwhelmed logged. One pebble at a time.',
    'Too much? Do one small thing.',
    'Overload noted. Shrink the scope.',
    'Big pile. Start with one corner.',
    (t) => `Overwhelmed · ${t}. Tiny step season.`,
    'No sorting. Just the next action.',
    'Pressure up. Scope down. Classic.',
    "Choose one. That's the whole job.",
    'One line. One move. Nothing else.',
    "You don't need the whole plan. Just start.",
    'Too many tabs. Close to one.',
    "Overwhelmed, but moving. That's brave.",
  ],
}

export function pickToast(templates: ToastTemplate[], time: string): string {
  const template = templates[Math.floor(Math.random() * templates.length)]
  return typeof template === 'function' ? template(time) : template
}
